import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import styles from '../styles/AddInvoice.module.css'
import Form from '../components/Form'

export default function addInvoice() {

    return (
        <div className={`container`}>
            <Head>
                <title>Invoices | Add Invoice</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="main">
                <Navbar />
                <h1>Add new invoice:</h1>
                <Form />
            </main>

            <Footer />
        </div>
    )
}
